// <auto-generated />
using System;
using Karamchari.Performance.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Karamchari.Performance.Migrations
{
    [DbContext(typeof(PerformanceDbContext))]
    partial class PerformanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("__tenant__")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Karamchari.Performance.Domain.Calibration.CalibrationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BellCurvePolicy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("FinalizedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ReviewCycleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ReviewCycleId", "Name")
                        .IsUnique();

                    b.ToTable("CalibrationSessions", "__tenant__");
                });

            modelBuilder.Entity("Karamchari.Performance.Domain.Career.CareerFramework", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("CareerFrameworks", "__tenant__");
                });

            modelBuilder.Entity("Karamchari.Performance.Domain.Career.EmployeeGrowthPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateOnly>("TargetDate")
                        .HasColumnType("date");

                    b.Property<string>("TargetLevelDisplay")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("TargetLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "EmployeeId", "Status");

                    b.ToTable("EmployeeGrowthPlans", "__tenant__");
                });

            modelBuilder.Entity("Karamchari.Performance.Domain.Feedback.FeedbackRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Context")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("ExpiresOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("FeedbackProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("bit");

                    b.Property<Guid>("RequestedByEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("SubjectEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "SubjectEmployeeId", "Status");

                    b.ToTable("FeedbackRequests", "__tenant__");
                });

            modelBuilder.Entity("Karamchari.Performance.Domain.Feedback.FeedbackSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnonymityToken")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("GrowthAreasNarrative")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("bit");

                    b.Property<string>("OverallComment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal?>("Rating")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StrengthsNarrative")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("SubjectEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("SubmittedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "SubjectEmployeeId", "Status");

                    b.ToTable("FeedbackSubmissions", "__tenant__");
                });

            modelBuilder.Entity("Karamchari.Performance.Domain.Goals.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CurrentProgress")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CycleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal?>("FinalScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OwnerType")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParentGoalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TargetValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CycleId", "OwnerId");

                    b.ToTable("Goals", "__tenant__");
                });

            modelBuilder.Entity("Karamchari.Performance.Domain.Goals.GoalCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name", "Type", "StartDate")
                        .IsUnique();

                    b.ToTable("GoalCycles", "__tenant__");
                });

            modelBuilder.Entity("Karamchari.Performance.Domain.KPIs.KPIDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Aggregation")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FormulaExpression")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Periodicity")
                        .HasColumnType("int");

                    b.Property<int>("Polarity")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.ToTable("KPIDefinitions", "__tenant__");
                });

            modelBuilder.Entity("Karamchari.Performance.Domain.KPIs.KPIResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ComputedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KPIDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("NormalizedScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid?>("OverriddenBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OverrideJustification")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<string>("PeriodLabel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<decimal>("RawValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "KPIDefinitionId", "EmployeeId", "PeriodLabel");

                    b.ToTable("KPIResults", "__tenant__");
                });

            modelBuilder.Entity("Karamchari.Performance.Domain.KPIs.KPISnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Band")
                        .HasColumnType("int");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("KPICode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("KPIDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("KPIDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("NormalizedScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("PeriodLabel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("SnapshotTakenUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "EmployeeId", "KPIDefinitionId", "PeriodLabel");

                    b.ToTable("KPISnapshots", "__tenant__");
                });

            modelBuilder.Entity("Karamchari.Performance.Domain.OKRs.OKRCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Scope")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("OKRCycles", "__tenant__");
                });

            modelBuilder.Entity("Karamchari.Performance.Domain.OKRs.Objective", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AggregatedScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CycleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsStretch")
                        .HasColumnType("bit");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OwnerType")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParentObjectiveId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CycleId", "OwnerId");

                    b.ToTable("Objectives", "__tenant__");
                });

            modelBuilder.Entity("Karamchari.Performance.Domain.Promotions.PromotionRecommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("ApprovedEffectiveDate")
                        .HasColumnType("date");

                    b.Property<string>("CurrentGrade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CurrentTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("NominatedByManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("ProposedEffectiveDate")
                        .HasColumnType("date");

                    b.Property<string>("ProposedGrade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProposedTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("ReadinessScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "EmployeeId", "Status");

                    b.ToTable("PromotionRecommendations", "__tenant__");
                });

            modelBuilder.Entity("Karamchari.Performance.Domain.ReadModels.CalibrationBoardProjection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AdjustmentsMade")
                        .HasColumnType("int");

                    b.Property<int>("BelowExpectationsCount")
                        .HasColumnType("int");

                    b.Property<Guid>("CalibrationSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EntriesPendingFinalization")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("FinalizedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("HighPerformerCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastRefreshedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MeetsExpectationsCount")
                        .HasColumnType("int");

                    b.Property<int>("PanelMembersJoined")
                        .HasColumnType("int");

                    b.Property<Guid>("ReviewCycleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TopPerformerCount")
                        .HasColumnType("int");

                    b.Property<int>("TotalEntries")
                        .HasColumnType("int");

                    b.Property<int>("TotalPanelMembers")
                        .HasColumnType("int");

                    b.Property<int>("UnderPerformerCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CalibrationSessionId")
                        .IsUnique()
                        .HasDatabaseName("UIX_CalibrationBoardProjections_Session");

                    b.HasIndex("TenantId", "ReviewCycleId")
                        .HasDatabaseName("IX_CalibrationBoardProjections_Cycle");

                    b.ToTable("CalibrationBoardProjections", "__tenant__");
                });

            modelBuilder.Entity("Karamchari.Performance.Domain.ReadModels.EmployeeSkillInventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CareerLevel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CurrentProficiency")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("EmployeeDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("LastAssessedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastAssessmentSource")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("LastRefreshedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ProficiencyGap")
                        .HasColumnType("int");

                    b.Property<string>("SkillCategoryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TargetProficiency")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Department", "Domain")
                        .HasDatabaseName("IX_EmployeeSkillInventoryItems_Dept_Domain");

                    b.HasIndex("TenantId", "EmployeeId", "SkillId")
                        .IsUnique()
                        .HasDatabaseName("UIX_EmployeeSkillInventoryItems_Employee_Skill");

                    b.HasIndex("TenantId", "SkillId", "CurrentProficiency")
                        .HasDatabaseName("IX_EmployeeSkillInventoryItems_Skill_Proficiency");

                    b.ToTable("EmployeeSkillInventoryItems", "__tenant__");
                });

            modelBuilder.Entity("Karamchari.Performance.Domain.ReadModels.ManagerDashboardProjection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CycleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("GoalCompletionRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("KPIsAtRisk")
                        .HasColumnType("int");

                    b.Property<int>("KPIsOffTrack")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastRefreshedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ManagerEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OffTrackGoals")
                        .HasColumnType("int");

                    b.Property<int>("OnTrackGoals")
                        .HasColumnType("int");

                    b.Property<int>("OverdueGoals")
                        .HasColumnType("int");

                    b.Property<int>("PendingApprovals")
                        .HasColumnType("int");

                    b.Property<int>("PendingFeedbackRequests")
                        .HasColumnType("int");

                    b.Property<int>("PendingPromotionApprovals")
                        .HasColumnType("int");

                    b.Property<Guid>("ReviewCycleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReviewsCompleted")
                        .HasColumnType("int");

                    b.Property<int>("ReviewsOverdue")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TotalReviewsRequired")
                        .HasColumnType("int");

                    b.Property<int>("TotalTeamGoals")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ManagerEmployeeId", "ReviewCycleId")
                        .IsUnique()
                        .HasDatabaseName("UIX_ManagerDashboardProjections_Manager_Cycle");

                    b.ToTable("ManagerDashboardProjections", "__tenant__");
                });

            modelBuilder.Entity("Karamchari.Performance.Domain.ReadModels.PerformanceSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CompositeScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("CycleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("GoalCompletionRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsAtRetentionRisk")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHighPerformer")
                        .HasColumnType("bit");

                    b.Property<decimal?>("KPIScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTimeOffset>("MaterializedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("OKRScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("PeerFeedbackScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("PerformanceBucket")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ReviewCycleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("ReviewPeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ReviewPeriodStart")
                        .HasColumnType("date");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "EmployeeId", "ReviewCycleId");

                    b.HasIndex("TenantId", "IsHighPerformer", "IsAtRetentionRisk");

                    b.ToTable("PerformanceSnapshots", "__tenant__");
                });

            modelBuilder.Entity("Karamchari.Performance.Domain.ReadModels.PromotionPipelineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrentCareerLevel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DaysInCurrentStage")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmployeeDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("LastRefreshedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PromotionRecommendationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProposedCareerLevel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("ReadinessScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("ReviewCycleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "PromotionRecommendationId")
                        .IsUnique()
                        .HasDatabaseName("UIX_PromotionPipelineItems_Recommendation");

                    b.HasIndex("TenantId", "ReviewCycleId", "Status")
                        .HasDatabaseName("IX_PromotionPipelineItems_Cycle_Status");

                    b.ToTable("PromotionPipelineItems", "__tenant__");
                });

            modelBuilder.Entity("Karamchari.Performance.Domain.ReadModels.ReviewTaskInboxItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CycleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("Deadline")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("HoursUntilDeadline")
                        .HasColumnType("int");

                    b.Property<bool>("IsOverdue")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastRefreshedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<Guid>("ReviewAssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReviewCycleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RevieweeDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("RevieweeEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReviewerEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReviewerRole")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ReviewAssignmentId")
                        .IsUnique()
                        .HasDatabaseName("UIX_ReviewTaskInboxItems_Assignment");

                    b.HasIndex("TenantId", "ReviewerEmployeeId", "Priority")
                        .HasDatabaseName("IX_ReviewTaskInboxItems_Reviewer_Priority");

                    b.ToTable("ReviewTaskInboxItems", "__tenant__");
                });

            modelBuilder.Entity("Karamchari.Performance.Domain.ReadModels.TalentHeatmapEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CareerLevel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("CompositeScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("CycleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmployeeDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAtRetentionRisk")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHighPerformer")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPromotionReady")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuccessionCandidate")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastRefreshedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("MaterializedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NineBoxPosition")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PerformanceBucket")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PotentialRating")
                        .HasColumnType("int");

                    b.Property<Guid>("ReviewCycleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Department", "ReviewCycleId")
                        .HasDatabaseName("IX_TalentHeatmapEntries_Dept_Cycle");

                    b.HasIndex("TenantId", "EmployeeId", "ReviewCycleId")
                        .IsUnique()
                        .HasDatabaseName("UIX_TalentHeatmapEntries_Employee_Cycle");

                    b.HasIndex("TenantId", "NineBoxPosition", "ReviewCycleId")
                        .HasDatabaseName("IX_TalentHeatmapEntries_NineBox_Cycle");

                    b.ToTable("TalentHeatmapEntries", "__tenant__");
                });

            modelBuilder.Entity("Karamchari.Performance.Domain.ReadModels.TeamGoalSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AverageProgress")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("CompletedGoals")
                        .HasColumnType("int");

                    b.Property<decimal>("CompletionRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("CycleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EmployeesWithNoGoals")
                        .HasColumnType("int");

                    b.Property<Guid>("GoalCycleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("InProgressGoals")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastRefreshedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ManagerEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NotStartedGoals")
                        .HasColumnType("int");

                    b.Property<int>("OffTrackGoals")
                        .HasColumnType("int");

                    b.Property<int>("TeamSize")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TotalGoals")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ManagerEmployeeId", "GoalCycleId")
                        .IsUnique()
                        .HasDatabaseName("UIX_TeamGoalSummaries_Manager_Cycle");

                    b.ToTable("TeamGoalSummaries", "__tenant__");
                });

            modelBuilder.Entity("Karamchari.Performance.Domain.Reporting.ExportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobUri")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset?>("CompletedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("RequestedByEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .HasDatabaseName("IX_ExportJobs_IdempotencyKey");

                    b.HasIndex("TenantId", "RequestedByEmployeeId", "Status")
                        .HasDatabaseName("IX_ExportJobs_Tenant_Employee_Status");

                    b.HasIndex("TenantId", "Status", "CreatedOnUtc")
                        .HasDatabaseName("IX_ExportJobs_Status_CreatedAt");

                    b.ToTable("ExportJobs", "__tenant__");
                });

            modelBuilder.Entity("Karamchari.Performance.Domain.Reviews.ReviewAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CycleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsFinalized")
                        .HasColumnType("bit");

                    b.Property<Guid>("RevieweeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReviewerSlots")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CycleId", "RevieweeId")
                        .IsUnique();

                    b.ToTable("ReviewAssignments", "__tenant__");
                });

            modelBuilder.Entity("Karamchari.Performance.Domain.Reviews.ReviewCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CompletedAssignments")
                        .HasColumnType("int");

                    b.Property<Guid?>("GoalCycleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("OKRCycleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("ReviewPeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ReviewPeriodStart")
                        .HasColumnType("date");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateOnly>("SubmissionDeadline")
                        .HasColumnType("date");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("TotalAssignments")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name", "ReviewPeriodStart")
                        .IsUnique();

                    b.ToTable("ReviewCycles", "__tenant__");
                });

            modelBuilder.Entity("Karamchari.Performance.Domain.Reviews.ReviewSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AcknowledgedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ComputedScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReopenHistory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RevieweeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReviewerRole")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("SubmittedOnUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "AssignmentId", "ReviewerId");

                    b.ToTable("ReviewSubmissions", "__tenant__");
                });

            modelBuilder.Entity("Karamchari.Performance.Domain.Reviews.ReviewTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ApplicableCycleType")
                        .HasColumnType("int");

                    b.Property<bool>("IncludesManagerReview")
                        .HasColumnType("bit");

                    b.Property<bool>("IncludesPeerReview")
                        .HasColumnType("bit");

                    b.Property<bool>("IncludesSelfReview")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Sections")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("ReviewTemplates", "__tenant__");
                });

            modelBuilder.Entity("Karamchari.Performance.Domain.Skills.EmployeeSkillProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "EmployeeId")
                        .IsUnique();

                    b.ToTable("EmployeeSkillProfiles", "__tenant__");
                });

            modelBuilder.Entity("Karamchari.Performance.Domain.Skills.SkillTaxonomy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("SkillTaxonomies", "__tenant__");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Received")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Delivered");

                    b.ToTable("InboxState", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Properties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique()
                        .HasFilter("[OutboxId] IS NOT NULL");

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique()
                        .HasFilter("[InboxMessageId] IS NOT NULL AND [InboxConsumerId] IS NOT NULL");

                    b.ToTable("OutboxMessage", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("datetime2");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.ToTable("OutboxState", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Karamchari.Performance.Domain.Calibration.CalibrationSession", b =>
                {
                    b.OwnsMany("Karamchari.Performance.Domain.Calibration.CalibrationEntry", "Entries", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CalibratedBucket")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<decimal>("CalibratedScore")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)");

                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("IsFinalized")
                                .HasColumnType("bit");

                            b1.Property<string>("PreCalibrationBucket")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.Property<decimal>("PreCalibrationScore")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)");

                            b1.Property<Guid>("SessionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("TenantId")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)");

                            b1.HasKey("Id");

                            b1.HasIndex("SessionId", "EmployeeId")
                                .IsUnique()
                                .HasDatabaseName("IX_CalibrationEntries_Session_Employee");

                            b1.ToTable("CalibrationEntries", "__tenant__");

                            b1.WithOwner()
                                .HasForeignKey("SessionId");

                            b1.OwnsMany("Karamchari.Performance.Domain.Calibration.CalibrationAdjustmentRecord", "Adjustments", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("AdjustedBy")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<DateTimeOffset>("AdjustedOnUtc")
                                        .HasColumnType("datetimeoffset");

                                    b2.Property<Guid>("CalibrationEntryId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Justification")
                                        .IsRequired()
                                        .HasMaxLength(1000)
                                        .HasColumnType("nvarchar(1000)");

                                    b2.Property<string>("NewBucket")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)");

                                    b2.Property<decimal>("NewScore")
                                        .HasPrecision(5, 2)
                                        .HasColumnType("decimal(5,2)");

                                    b2.Property<string>("PreviousBucket")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)");

                                    b2.Property<decimal>("PreviousScore")
                                        .HasPrecision(5, 2)
                                        .HasColumnType("decimal(5,2)");

                                    b2.HasKey("Id");

                                    b2.HasIndex("CalibrationEntryId");

                                    b2.ToTable("CalibrationAdjustmentRecords", "__tenant__");

                                    b2.WithOwner()
                                        .HasForeignKey("CalibrationEntryId");
                                });

                            b1.Navigation("Adjustments");
                        });

                    b.OwnsMany("Karamchari.Performance.Domain.Calibration.CalibrationPanelMember", "PanelMembers", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Role")
                                .HasColumnType("int");

                            b1.Property<Guid>("SessionId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("SessionId");

                            b1.ToTable("CalibrationPanelMembers", "__tenant__");

                            b1.WithOwner()
                                .HasForeignKey("SessionId");
                        });

                    b.Navigation("Entries");

                    b.Navigation("PanelMembers");
                });

            modelBuilder.Entity("Karamchari.Performance.Domain.Career.CareerFramework", b =>
                {
                    b.OwnsMany("Karamchari.Performance.Domain.Career.CareerTrack", "Tracks", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Description")
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)");

                            b1.Property<Guid>("FrameworkId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("TenantId")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("FrameworkId");

                            b1.ToTable("CareerTracks", "__tenant__");

                            b1.WithOwner()
                                .HasForeignKey("FrameworkId");

                            b1.OwnsMany("Karamchari.Performance.Domain.Career.CareerLevel", "Levels", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("nvarchar(20)");

                                    b2.Property<string>("CompetencyRequirements")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("Description")
                                        .HasMaxLength(1000)
                                        .HasColumnType("nvarchar(1000)");

                                    b2.Property<string>("DisplayName")
                                        .IsRequired()
                                        .HasMaxLength(100)
                                        .HasColumnType("nvarchar(100)");

                                    b2.Property<int>("Order")
                                        .HasColumnType("int");

                                    b2.Property<Guid>("TrackId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.HasKey("Id");

                                    b2.HasIndex("TrackId", "Order")
                                        .IsUnique()
                                        .HasDatabaseName("IX_CareerLevels_Track_Order");

                                    b2.ToTable("CareerLevels", "__tenant__");

                                    b2.WithOwner()
                                        .HasForeignKey("TrackId");
                                });

                            b1.Navigation("Levels");
                        });

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Karamchari.Performance.Domain.Career.EmployeeGrowthPlan", b =>
                {
                    b.OwnsMany("Karamchari.Performance.Domain.Career.DevelopmentAction", "Actions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly?>("CompletedOnDate")
                                .HasColumnType("date");

                            b1.Property<string>("CompletionNotes")
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)");

                            b1.Property<string>("Description")
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)");

                            b1.Property<Guid>("GrowthPlanId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Status")
                                .HasColumnType("int");

                            b1.Property<DateOnly?>("TargetCompletionDate")
                                .HasColumnType("date");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("GrowthPlanId");

                            b1.ToTable("DevelopmentActions", "__tenant__");

                            b1.WithOwner()
                                .HasForeignKey("GrowthPlanId");
                        });

                    b.Navigation("Actions");
                });

            modelBuilder.Entity("Karamchari.Performance.Domain.Goals.Goal", b =>
                {
                    b.OwnsMany("Karamchari.Performance.Domain.Goals.GoalProgressUpdate", "Updates", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("GoalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Notes")
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)");

                            b1.Property<DateTimeOffset>("OccurredOnUtc")
                                .HasColumnType("datetimeoffset");

                            b1.Property<decimal>("ProgressPercent")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)");

                            b1.Property<Guid>("UpdatedBy")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)");

                            b1.HasKey("Id");

                            b1.HasIndex("GoalId");

                            b1.ToTable("GoalProgressUpdates", "__tenant__");

                            b1.WithOwner()
                                .HasForeignKey("GoalId");
                        });

                    b.OwnsMany("Karamchari.Performance.Domain.Goals.GoalRevisionRecord", "Revisions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("GoalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("NewTarget")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("NewTitle")
                                .IsRequired()
                                .HasMaxLength(400)
                                .HasColumnType("nvarchar(400)");

                            b1.Property<DateTimeOffset>("OccurredOnUtc")
                                .HasColumnType("datetimeoffset");

                            b1.Property<decimal>("PreviousTarget")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("PreviousTitle")
                                .IsRequired()
                                .HasMaxLength(400)
                                .HasColumnType("nvarchar(400)");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)");

                            b1.Property<Guid>("RevisedBy")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("GoalId");

                            b1.ToTable("GoalRevisionRecords", "__tenant__");

                            b1.WithOwner()
                                .HasForeignKey("GoalId");
                        });

                    b.Navigation("Revisions");

                    b.Navigation("Updates");
                });

            modelBuilder.Entity("Karamchari.Performance.Domain.KPIs.KPIDefinition", b =>
                {
                    b.OwnsOne("Karamchari.Performance.Domain.KPIs.KPIThreshold", "Threshold", b1 =>
                        {
                            b1.Property<Guid>("KPIDefinitionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("GreenAbove")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)");

                            b1.Property<decimal>("RedBelow")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)");

                            b1.Property<decimal>("YellowBelow")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)");

                            b1.HasKey("KPIDefinitionId");

                            b1.ToTable("KPIDefinitions", "__tenant__");

                            b1.WithOwner()
                                .HasForeignKey("KPIDefinitionId");
                        });

                    b.Navigation("Threshold")
                        .IsRequired();
                });

            modelBuilder.Entity("Karamchari.Performance.Domain.OKRs.Objective", b =>
                {
                    b.OwnsMany("Karamchari.Performance.Domain.OKRs.KeyResult", "KeyResults", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("ConfidenceLevel")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("CurrentValue")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)");

                            b1.Property<Guid?>("DependsOnKrId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset?>("LastCheckInUtc")
                                .HasColumnType("datetimeoffset");

                            b1.Property<Guid>("ObjectiveId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("ProgressPercent")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal>("Score")
                                .HasPrecision(5, 4)
                                .HasColumnType("decimal(5,4)");

                            b1.Property<int>("Status")
                                .HasColumnType("int");

                            b1.Property<decimal>("Target")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(400)
                                .HasColumnType("nvarchar(400)");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<decimal>("Weight")
                                .HasPrecision(5, 4)
                                .HasColumnType("decimal(5,4)");

                            b1.HasKey("Id");

                            b1.HasIndex("ObjectiveId");

                            b1.ToTable("KeyResults", "__tenant__");

                            b1.WithOwner()
                                .HasForeignKey("ObjectiveId");

                            b1.OwnsMany("Karamchari.Performance.Domain.OKRs.KRCheckIn", "CheckIns", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("ConfidenceLevel")
                                        .HasColumnType("decimal(18,2)");

                                    b2.Property<Guid>("KeyResultId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Notes")
                                        .HasMaxLength(1000)
                                        .HasColumnType("nvarchar(1000)");

                                    b2.Property<DateTimeOffset>("OccurredOnUtc")
                                        .HasColumnType("datetimeoffset");

                                    b2.Property<Guid>("UpdatedBy")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Value")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("decimal(18,4)");

                                    b2.HasKey("Id");

                                    b2.HasIndex("KeyResultId");

                                    b2.ToTable("KRCheckIns", "__tenant__");

                                    b2.WithOwner()
                                        .HasForeignKey("KeyResultId");
                                });

                            b1.Navigation("CheckIns");
                        });

                    b.Navigation("KeyResults");
                });

            modelBuilder.Entity("Karamchari.Performance.Domain.Promotions.PromotionRecommendation", b =>
                {
                    b.OwnsMany("Karamchari.Performance.Domain.Promotions.PromotionApprovalAction", "ApprovalActions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset>("ActedOnUtc")
                                .HasColumnType("datetimeoffset");

                            b1.Property<Guid>("ActorId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("Approved")
                                .HasColumnType("bit");

                            b1.Property<string>("Comments")
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)");

                            b1.Property<Guid>("RecommendationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Stage")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("RecommendationId");

                            b1.ToTable("PromotionApprovalActions", "__tenant__");

                            b1.WithOwner()
                                .HasForeignKey("RecommendationId");
                        });

                    b.Navigation("ApprovalActions");
                });

            modelBuilder.Entity("Karamchari.Performance.Domain.Reviews.ReviewSubmission", b =>
                {
                    b.OwnsMany("Karamchari.Performance.Domain.Reviews.ReviewResponse", "Responses", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("QuestionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("QuestionType")
                                .HasColumnType("int");

                            b1.Property<decimal?>("RatingValue")
                                .HasPrecision(5, 2)
                                .HasColumnType("decimal(5,2)");

                            b1.Property<Guid>("SubmissionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("TextValue")
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)");

                            b1.HasKey("Id");

                            b1.HasIndex("SubmissionId");

                            b1.ToTable("ReviewResponses", "__tenant__");

                            b1.WithOwner()
                                .HasForeignKey("SubmissionId");
                        });

                    b.Navigation("Responses");
                });

            modelBuilder.Entity("Karamchari.Performance.Domain.Skills.EmployeeSkillProfile", b =>
                {
                    b.OwnsMany("Karamchari.Performance.Domain.Skills.EmployeeSkillAssessment", "Assessments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("AssessedByEmployeeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset>("AssessedOnUtc")
                                .HasColumnType("datetimeoffset");

                            b1.Property<string>("Evidence")
                                .HasMaxLength(2000)
                                .HasColumnType("nvarchar(2000)");

                            b1.Property<int>("Level")
                                .HasColumnType("int");

                            b1.Property<Guid>("ProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("SkillId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Source")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("ProfileId", "SkillId", "AssessedOnUtc")
                                .HasDatabaseName("IX_SkillAssessments_Profile_Skill_Date");

                            b1.ToTable("EmployeeSkillAssessments", "__tenant__");

                            b1.WithOwner()
                                .HasForeignKey("ProfileId");
                        });

                    b.Navigation("Assessments");
                });

            modelBuilder.Entity("Karamchari.Performance.Domain.Skills.SkillTaxonomy", b =>
                {
                    b.OwnsMany("Karamchari.Performance.Domain.Skills.SkillCategory", "Categories", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Description")
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<Guid>("TaxonomyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("TenantId")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("nvarchar(60)");

                            b1.HasKey("Id");

                            b1.HasIndex("TaxonomyId");

                            b1.ToTable("SkillCategories", "__tenant__");

                            b1.WithOwner()
                                .HasForeignKey("TaxonomyId");

                            b1.OwnsMany("Karamchari.Performance.Domain.Skills.Skill", "Skills", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("CategoryId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Description")
                                        .HasMaxLength(1000)
                                        .HasColumnType("nvarchar(1000)");

                                    b2.Property<int>("Domain")
                                        .HasColumnType("int");

                                    b2.Property<bool>("IsActive")
                                        .HasColumnType("bit");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("nvarchar(200)");

                                    b2.Property<string>("ProficiencyDescriptors")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("TenantId")
                                        .IsRequired()
                                        .HasMaxLength(60)
                                        .HasColumnType("nvarchar(60)");

                                    b2.HasKey("Id");

                                    b2.HasIndex("CategoryId");

                                    b2.HasIndex("TenantId", "Name", "Domain")
                                        .HasDatabaseName("IX_Skills_Tenant_Name_Domain");

                                    b2.ToTable("Skills", "__tenant__");

                                    b2.WithOwner()
                                        .HasForeignKey("CategoryId");
                                });

                            b1.Navigation("Skills");
                        });

                    b.Navigation("Categories");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId");
                });
#pragma warning restore 612, 618
        }
    }
}
