/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        // Karamchari institutional palette — CSS-var backed so the whole token
        // system inverts at night (light values + html.dark overrides in index.css).
        primary: { DEFAULT: "#000000", foreground: "#ffffff" },
        secondary: { DEFAULT: "#615e57", foreground: "#ffffff" },
        background: "var(--c-bg)",
        surface: "var(--c-surface)",
        "surface-dim": "var(--c-surface-dim)",
        "surface-bright": "var(--c-surface-bright)",
        "surface-container-lowest": "var(--c-sc-lowest)",
        "surface-container-low": "var(--c-sc-low)",
        "surface-container": "var(--c-sc)",
        "surface-container-high": "var(--c-sc-high)",
        "surface-container-highest": "var(--c-sc-highest)",
        "surface-variant": "var(--c-surface-variant)",
        "surface-tint": "#5e5e62",
        "on-surface": "var(--c-on-surface)",
        "on-surface-variant": "var(--c-on-surface-variant)",
        "on-background": "var(--c-on-bg)",
        "inverse-surface": "#313030",
        "inverse-on-surface": "#f4f0ef",
        outline: "var(--c-outline)",
        "outline-variant": "var(--c-outline-variant)",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "secondary-container": "var(--c-secondary-container)",
        "on-secondary-container": "var(--c-on-secondary-container)",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        // Brand voices
        "yantra-indigo": "#1B2A4E",
        "yantra-indigo-2": "#2A3D6B",
        "sthira-forest": "#2D5D4B",
        "tamra-copper": "#B16A3C",
        "tamra-copper-bright": "#C68A60",
        "hiranya-gold": "#C9A86A",
        graphite: "#2A2D33",
        cloud: "#D9D2C2",
        ivory: "#F2EDE3",
        "ivory-2": "#ECE6D9",
        "ivory-3": "#E3DCCB",
        ink: "#0E0F12",
        "ink-2": "#1A1C21",
        "rakta-critical": "#7A2B2B",
        "pita-caution": "#9C842A",
      },
      spacing: {
        unit: "8px",
        "page-margin": "64px",
        "grid-12": "12px",
        "section-padding": "96px",
        gutter: "48px",
      },
      fontFamily: {
        serif: ["Newsreader", "Georgia", "serif"],
        sans: ["Geist", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "monospace"],
        "display-xl": ["Newsreader", "serif"],
        "section-title": ["Newsreader", "serif"],
        "pull-quote": ["Newsreader", "serif"],
        "body-standard": ["Geist", "sans-serif"],
        "tabular-data": ["Geist", "sans-serif"],
        "mono-label": ["JetBrains Mono", "monospace"],
        "display-xl-mobile": ["Newsreader", "serif"],
      },
      fontSize: {
        "display-xl": ["124px", { lineHeight: "0.94", letterSpacing: "-0.035em", fontWeight: "300" }],
        "display-xl-mobile": ["72px", { lineHeight: "1.0", fontWeight: "300" }],
        "section-title": ["56px", { lineHeight: "1.02", letterSpacing: "-0.02em", fontWeight: "300" }],
        "pull-quote": ["32px", { lineHeight: "1.2", letterSpacing: "-0.015em", fontWeight: "300" }],
        "body-standard": ["15px", { lineHeight: "1.55", fontWeight: "400" }],
        "tabular-data": ["14px", { lineHeight: "1.4", fontWeight: "400" }],
        "mono-label": ["10.5px", { lineHeight: "1.2", letterSpacing: "0.12em", fontWeight: "500" }],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
