namespace Karamchari.Intelligence.Domain.Workforce;

/// <summary>Score bands for burnout and attrition risk.</summary>
public enum WorkforceRiskLevel
{
    Low = 0,
    Moderate = 1,
    High = 2,
    Critical = 3
}

/// <summary>Data completeness confidence for scores derived from limited history.</summary>
public enum WorkforceScoreConfidence
{
    Low = 0,    // < 60 days data
    Medium = 1, // 60–89 days data
    High = 2    // ≥ 90 days data
}

/// <summary>Category of workforce recommendation generated by the engine.</summary>
public enum WorkforceRecommendationType
{
    ReduceOvertime,
    ScheduleLeave,
    ReduceConsecutiveShifts,
    ManagerCheckIn,
    TeamReassignmentReview,
    WorkloadAnalysis,
    RebalanceStaffing,
    IncreaseLeaveApproval,
    ReduceOtReliance,
    MonitorAttendance,
    ResetBaseline
}

/// <summary>Priority ordering for surfacing recommendations to managers.</summary>
public enum RecommendationPriority
{
    Low = 0,
    Medium = 1,
    High = 2,
    Critical = 3
}
