namespace Karamchari.TimeAttendance.Domain.IoT;

using Karamchari.Core.Multitenancy;

/// <summary>
/// Type of punch received from hardware or mobile.
/// </summary>
public enum PunchType
{
    Unknown = 0,
    In = 1,
    Out = 2
}

/// <summary>
/// Source of the punch event.
/// </summary>
public enum PunchSource
{
    Biometric = 1,
    Mobile = 2,
    Web = 3,
    Manual = 4 // Added by HR
}

/// <summary>
/// The immutable, sanitized source-of-truth for an employee punch.
/// All downstream business logic (reconciliation, payroll) operates on this data.
/// Never delete this record; it is the audit foundation.
/// </summary>
public sealed class RawPunch : ITenantOwned
{
    public string TenantId { get; private set; } = string.Empty;

    public Guid Id { get; private set; }

    public Guid EmployeeId { get; private set; }

    public string DeviceId { get; private set; } = string.Empty;

    /// <summary>
    /// The unique identifier generated by the source device. 
    /// Used for strict idempotency (UNIQUE constraint).
    /// </summary>
    public string ExternalId { get; private set; } = string.Empty;

    /// <summary>The UTC timestamp of the punch (from the device, converted to UTC).</summary>
    public DateTime TimestampUtc { get; private set; }

    /// <summary>The local timestamp of the punch (for reconciliation logic).</summary>
    public DateTime LocalTimestamp { get; private set; }

    /// <summary>The timezone of the local timestamp.</summary>
    public string TimeZone { get; private set; } = string.Empty;

    /// <summary>When the edge ingestion API actually received the payload.</summary>
    public DateTime ReceivedAt { get; private set; }

    public PunchType Type { get; private set; }

    public PunchSource Source { get; private set; }

    public double? Latitude { get; private set; }
    public double? Longitude { get; private set; }

    /// <summary>Indicates if this punch has been processed by the reconciliation engine.</summary>
    public bool IsProcessed { get; private set; }

    /// <summary>Tracks the version of the reconciliation engine that processed this punch.</summary>
    public string? ProcessedVersion { get; private set; }

    private RawPunch() { }

    public static RawPunch Create(
        string tenantId,
        Guid employeeId,
        string deviceId,
        string externalId,
        DateTime timestampUtc,
        DateTime localTimestamp,
        string timeZone,
        DateTime receivedAt,
        PunchType type,
        PunchSource source,
        double? latitude = null,
        double? longitude = null)
    {
        return new RawPunch
        {
            Id = Guid.NewGuid(),
            TenantId = tenantId,
            EmployeeId = employeeId,
            DeviceId = deviceId,
            ExternalId = externalId,
            TimestampUtc = timestampUtc,
            LocalTimestamp = localTimestamp,
            TimeZone = timeZone,
            ReceivedAt = receivedAt,
            Type = type,
            Source = source,
            Latitude = latitude,
            Longitude = longitude,
            IsProcessed = false
        };
    }

    /// <summary>
    /// Marks the punch as processed by a specific engine version.
    /// </summary>
    public void MarkProcessed(string version)
    {
        IsProcessed = true;
        ProcessedVersion = version;
    }
}
