<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Karamchari.Recruitment.Contracts</RootNamespace>
    <AssemblyName>Karamchari.Recruitment.Contracts</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Platform\Karamchari.Core.Contracts\Karamchari.Core.Contracts.csproj" />
  </ItemGroup>

</Project>
